# Generated by Django 3.0.8 on 2020-07-17 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adOfRoommate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adofroommate',
            name='date_publish',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 16, 22, 16, 320453)),
        ),
        migrations.AddField(
            model_name='adofroommate',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
