# Generated by Django 3.0.8 on 2020-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('houseArea', models.IntegerField()),
                ('roommmateNum', models.IntegerField()),
                ('roomNum', models.IntegerField()),
                ('wcNum', models.IntegerField()),
                ('ageOfHouse', models.IntegerField()),
                ('parking', models.BooleanField()),
            ],
        ),
    ]
